loki:
  global:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-credentials
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    compactor:
      retention_enabled: true
      delete_request_store: s3
    limits_config:
      ingestion_rate_strategy: local
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      retention_period: 14d
      max_query_lookback: 14d
      max_query_series: 100000
      allow_structured_metadata: true
      discover_log_levels: true
      discover_service_name:
        - k8s_deployment_name
        - k8s_daemonset_name
        - k8s_statefulset_name
        - k8s_cronjob_name
        - k8s_job_name
        - k8s_container_name
      otlp_config:
        scope_attributes: []
        log_attributes: []
        resource_attributes:
          ignore_defaults: true
          attributes_config:
            # other attributes are converted to structured_metadata
            - action: index_label
              attributes:
                - k8s.namespace.name
            - action: index_label
              attributes:
                - k8s.deployment.name
            - action: index_label
              attributes:
                - k8s.daemonset.name
            - action: index_label
              attributes:
                - k8s.statefulset.name
            - action: index_label
              attributes:
                - k8s.cronjob.name
            - action: index_label
              attributes:
                - k8s.job.name
            - action: index_label
              attributes:
                - k8s.container.name
    schemaConfig:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      bucketNames:
        chunks: loki-bucket
        ruler: loki-bucket
        admin: loki-bucket
      type: s3
      s3:
        endpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
        region: us-east-1
        secretAccessKey: ${LOKI_S3_SECRET_KEY}
        accessKeyId: ${LOKI_S3_ACCESS_KEY}
        s3ForcePathStyle: true
        insecure: true
  test:
    enabled: false
  lokiCanary:
    enabled: false
  monitoring:
    rules:
      enabled: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  backend:
    replicas: 1
    persistence:
      size: 1Gi
  write:
    replicas: 2
    persistence:
      size: 2Gi
  read:
    replicas: 1
    persistence:
      size: 1Gi
  gateway:
    enabled: false
