apiVersion: v2
name: rook-ceph
description: A Helm chart for Kubernetes
type: application
version: 0.0.1

dependencies:
  - name: rook-ceph
    repository: https://charts.rook.io/release
    version: 1.18.8